# RBAC for EKS read-only IAM user
# Save as terraform/eks_readonly_rbac.yaml and apply with kubectl

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-readonly
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "nodes", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["logs"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-readonly-binding
subjects:
  - kind: Group
    name: eks-readonly
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks-readonly
  apiGroup: rbac.authorization.k8s.io
